### ISSUE TITLE
ChannelUserEvent fails to parse

### ISSUE THREAD

**Issue by Charles92011** [l3nz/ari4java#93] opened 2018-04-27 18:53 UTC
I'm receiving a failure on a ChannelUserevent
The event sends without exception, but when it's received I'm getting a Json mapping exception. 

The problem is the userEvent member of ChannlUserEvent, when I change it from a String to an Object it 
succeeds.

I wonder if it should be Map<String, String> since that's what's actually sent.

------------ SEND -----------
final String application = ari.getAppName();
final String eventSource = String.format("channel:%s", channelId); 
	
HashMap<String, String> variables = new HashMap<String, String>();
	
try 
{
	ari.events().userEvent(event, application, eventSource, variables);

------------ RECEIVE -----------
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {
  "type": "ChannelUserevent",
  "timestamp": "2018-04-26T18:25:12.040-0400",
  "eventname": "timer",
  "userevent": {
    "eventname": "timer"
  },
  "channel": {
    "id": "1524781509.944",
    "name": "PJSIP/8475213281-00000106",
    "state": "Up",
    "caller": {
      "name": "",
      "number": "8475213281"
    },
    "connected": {
      "name": "",
      "number": ""
    },
    "accountcode": "",
    "dialplan": {
      "context": "default",
      "exten": "8445910652",
      "priority": 3
    },
    "creationtime": "2018-04-26T18:25:09.995-0400",
    "language": "en"
  },
  "asterisk_id": "12:1f:6f:c4:64:88",
  "application": "testari3-charles1"
};

**Comment by vedga** [comment] 2019-04-04 06:44
You can apply following patches:

# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/codegen/ch/loway/oss/ari4java/codegen/models/ModelField.java
+++ b/codegen/ch/loway/oss/ari4java/codegen/models/ModelField.java
@@ -32,6 +32,8 @@
         if ( typeConcrete.startsWith("List") ) {
             String innerType = typeConcrete.substring(5, typeConcrete.length()-1);
             sb.append(" @JsonDeserialize( contentAs=").append(innerType).append(".class )\n");
+        } else if ( "Object".equals(typeConcrete) ) {
+            sb.append(" @JsonDeserialize( using=com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.class").append(" )\n");
         } else {
             sb.append(" @JsonDeserialize( as=").append(typeConcrete).append(".class )\n");
         }

# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/codegen/ch/loway/oss/ari4java/codegen/genJava/JavaPkgInfo.java
+++ b/codegen/ch/loway/oss/ari4java/codegen/genJava/JavaPkgInfo.java
@@ -21,7 +21,8 @@
         TypeMap.put( "int", "int" );
         TypeMap.put( "double", "double" );
         TypeMap.put( "date", "Date" );
-        TypeMap.put( "object", "String" );
+//        TypeMap.put( "object", "String" );
+        TypeMap.put( "object", "Object" );
         TypeMap.put( "boolean", "boolean" );
         TypeMap.put( "binary", "byte[]" );
         TypeMap.put( "containers", "Map<String,String>" );

**Comment by vedga** [comment] 2019-04-04 06:49
Hi,

You can apply following patches for fix this issue.

[UserEventPatches.zip](https://github.com/l3nz/ari4java/files/3042056/UserEventPatches.zip)

**Comment by grahambrown11** [comment] 2019-10-10 16:52
I'll have a look at the provided patch and possibly merge in, @Charles92011 were you able to test the change and verify it works? I've not used UserEvents, so I don't know how to generate and test this...

**Comment by Charles92011** [comment] 2019-10-10 17:00
@grahambrown11 We made this change on our fork well over a year ago:
![image](https://user-images.githubusercontent.com/6334019/66590002-a7fa1a00-eb44-11e9-8509-221409c6c413.png)

It's been in production ever since.

**Comment by grahambrown11** [comment] 2019-10-11 05:59
Duplicate of #12

**Closed by grahambrown11** 2019-10-11 05:59 UTC
Labels: duplicate
