### ISSUE TITLE
asterisk 16.5.1 have a new ARI version of 4.0.2

### ISSUE THREAD

**Issue by Rom1kz** [l3nz/ari4java#126] opened 2019-09-07 18:30 UTC
for example there is new fields in "dialplan" section
```
"dialplan": {
      "context": "office",
      "exten": "111",
      "priority": 1,
      "app_name": "Stasis",
      "app_data": "router"
    }
```

`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "app_name"`

**Comment by gmilit** [comment] 2019-09-30 04:18
I am having this same error, to get around this I have been using the fork from this pull request.
https://github.com/l3nz/ari4java/pull/124

It has been working well for me.

**Comment by grahambrown11** [comment] 2019-10-11 06:58
Duplicate of #124

**Closed by grahambrown11** 2019-10-11 06:58 UTC
Labels: duplicate
