### ISSUE TITLE
WS Reconnect 

### ISSUE THREAD

**Issue by grahambrown11** [l3nz/ari4java#26] opened 2015-02-03 13:50 UTC
Hi

I have a problem with the websocket connection being closed by Asterisk then I no longer receive events... Is there a way I can test the connection and reset it?

Here is a stack trace that is printed out on the console, but the onFailure callback is not called
```
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:243)
	at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:487)
	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:441)
	at org.apache.tomcat.websocket.WsFrameBase.processDataControl(WsFrameBase.java:324)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:270)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:116)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:54)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:194)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:203)
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:92)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:609)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at org.apache.tomcat.websocket.FutureToSendHandler.get(FutureToSendHandler.java:102)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:238)
	... 16 common frames omitted
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:128)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:185)
	at org.apache.coyote.http11.upgrade.NioServletOutputStream.doWriteInternal(NioServletOutputStream.java:94)
	at org.apache.coyote.http11.upgrade.NioServletOutputStream.doWrite(NioServletOutputStream.java:61)
	at org.apache.coyote.http11.upgrade.AbstractServletOutputStream.writeInternal(AbstractServletOutputStream.java:153)
	at org.apache.coyote.http11.upgrade.AbstractServletOutputStream.write(AbstractServletOutputStream.java:121)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.onWritePossible(WsRemoteEndpointImplServer.java:94)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:81)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:393)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessage(WsRemoteEndpointImplBase.java:287)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:233)
	... 16 common frames omitted 
```

BTW thank you for the API

**Comment by l3nz** [comment] 2015-02-04 10:07
When does this happen? Do you have a piece of code that reproduces this error?

**Comment by grahambrown11** [comment] 2015-02-04 17:50
Thanks for the reply.
To reproduce, create the ARI object with the Netty helper and supply the ActionEvent
```
ARI ari = AriFactory.nettyHttp(url, user, pass, AriVersion.ARI_1_5_0);
ActionEvents ae = ari.getActionImpl(ActionEvents.class);
ae.eventWebsocket("graham-dial", new AriCallback<Message>() {
    @Override
    public void onSuccess(Message message) {
        System.out.println("onSuccess");
        try {
            if (message instanceof StasisStart) {
                System.out.println("Start from " + ((StasisStart) message).getChannel().getCaller().getNumber());
            }
       } catch (Exception e) {
           e.printStackTrace();
       }
    }
    @Override
    public void onFailure(RestException e) {
        System.out.println("onFailure");
        e.printStackTrace();
    }
});
```
In my dial plan I have an extension that calls the Stasis app
```
same =>      n,Stasis(graham-dial)
```
Start the program and it will connect to the asterisk websocket. Shut down the asterisk server the start it up again (to emulate a network failure or whatever). Dial the extension - the program doesn't get the onSuccess or onFailure output. But eventually I get the stacktrace as mentioned above, unfortunately it's all in the org.apache namespace...

**Comment by l3nz** [comment] 2015-02-05 06:43
I think I understand what is going on.

We throw a RestException if a method fails - that is Asterisk tells us for example that a channel name is invalid. We are not trapping error codes coming from below that level.

Most likely,in a case like this, we should simply and automagically attempt reconnecting. If it does not work we should have a ConnectionException or something at the onFailure() level.

(Mike wrote the original Netty code so I'm not very familiar with it, but this needs checking. Want to leand a hand?).

**Comment by pta200** [comment] 2015-03-10 18:37
I posted about this too in the Google group as it's also a problem I'm having. I tried editing the  channelRead0 method in the NettyHttpClient class. Seems like when Asterisk is closing the socket (tested by restarting Asterisk) the client close message isn't bubbling up that far so you can't do a reconnect from there. Will keep looking.

**Comment by l3nz** [comment] 2015-03-11 09:29
This might be a pointer: http://stackoverflow.com/questions/11718718/websocket-connection-in-case-of-browser-crash

**Comment by pta200** [comment] 2015-03-18 20:40
OK I figured it out. In the AriAsyncHandler class nested inside the BaseAriAction class, the onDisconnect method doesn't do anything. This matters because the onDisconnect method is being called by the channelInactive method in the static HttpClientHandler class that's part of the NettyHttpClient class. By adding something like:

@Override
public void onDisconnect() {
          this.callback.onFailure(new RestException("Asterisk Disconnected"));
 }

to the AriAsyncHandler class the MessageQueue will get an error message if Asterisk drops/timeouts the websocket. 

At the moment there is no way to reconnect the event websocket if you use the getWebsocketQueue because the ActionEvents instance is a private attribute of the ARI class. You would need to create/manage your own MessageQueue and ActionEvent instances in order to restablish the websocket in the even that Asterisk just tied the previous one out.

**Comment by l3nz** [comment] 2015-03-20 12:03
Great job! I am refactoring those classes so it makes it easier to maintain them; plus of course I'll add a throw for a RestException when the connection goes down.

**Comment by l3nz** [comment] 2015-03-20 16:54
At the moment it won't reconnect automatically but at least you get an exception thrown: https://github.com/l3nz/ari4java/commit/bbcb9d5b4788b2bacef5d7e734c663cff034d24f

**Closed by l3nz** 2015-03-20 16:54 UTC
